CREATE TABLE IF NOT EXISTS blog.items (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title      VARCHAR(255) NOT NULL,
    message    TEXT,
    picture    BYTEA,
    likes      INTEGER,
    created    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS blog.comments
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    message    TEXT,
    item_id    INTEGER NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES blog.items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS blog.tags
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    tag        TEXT,
    CONSTRAINT pk_tag PRIMARY KEY (id),
    CONSTRAINT uq_tag UNIQUE (tag)
);

CREATE TABLE IF NOT EXISTS blog.items_tags
(
    item_id    INTEGER NOT NULL,
    tag_id     INTEGER NOT NULL,
    CONSTRAINT uk_item_tag UNIQUE (item_id, tag_id),
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES blog.items (id) ON DELETE CASCADE,
    CONSTRAINT fk_tag FOREIGN KEY (tag_id) REFERENCES blog.tags (id) ON DELETE CASCADE
);